name: Main CI

on:
  push:
    branches: [main, CI]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    name: Main CI
    runs-on: ubuntu-latest
    steps:
      - name: Build2 setup
        uses: build2/setup-build2-github-action@v2
      
      - name: Publish Build2 executables
        uses: actions/upload-artifact@v3
        with:
          name: build2-artifact
          path: |
            /usr/local/bin/b
            /usr/local/bin/bdep

      - name: Update system & install necessary tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3
          pip install compiledb
    
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: Sanity Checks
        uses: ./.github/workflows/sanity-checks.yaml

      - name: Build & Publish Documentation
        uses: ./.github/workflows/documentation.yaml
