name: CI

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    steps:  
      - name: checkout 
        uses: actions/checkout@v2

      - name: update system
        run: |
          sudo apt-get -y update
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3
          sudo apt-get -y install clang-tools-13
          pip install compiledb

      - name: install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: install Build2
        uses: build2/setup-build2-github-action@v2

      - name: setup project
        run: bdep init -C ../clang @clang cc config.c=clang config.cxx=clang++

      - name: compile project
        run: b

      - name: generate compilation database
        run: b -vn clean update |& compiledb

      - name: run unit tests
        run: b test

      - name: clang-format style check
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '13'

      - name: clang-tidy
        run: run-clang-tidy -p "./"
 
      - name: generate documentation
        run: doxygen Doxyfile

      - name: publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../i3-settings-docs/html/
