name: CI

on:
  push:
    branches: [main, CI]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    steps:  
      - name: Update system & install necessary tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3
          pip install compiledb
   
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: Install Build2
        uses: build2/setup-build2-github-action@v2

      - name: Setup project
        run: | 
          ls ./
          bdep init -C ../clang @clang cc config.c=clang config.cxx="clang++ -stdlib=libc++"

      - name: Compile project
        run: b

      - name: Generate compilation database
        run: b -vn clean update |& compiledb

      - name: Run unit tests
        run: b test

      - name: Clang-tidy Checks
        run: run-clang-tidy -p "./"
 
      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../i3-settings-docs/html/
