name: Main CI

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-build2:
    name: Compile build2
    runs-on: ubuntu-latest
    steps:
      - name: Build2 setup
        uses: build2/setup-build2-github-action@v2
      
      - name: Get location of Build2
        run: |
          which bdep
          which b

      - name: Publish Build2 executables
        uses: actions/upload-artifact@v3
        with:
          name: build2-artifact
          path: |
            /usr/local/bin/b
            /usr/local/bin/bdep

  documentation:
    name: Build Documentation & publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update system & install necessary tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3
          pip install compiledb
    
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: Get build2
        uses: actions/download-artifact@v3
        with:
          name: build2-artifact

      - name: Generate compilation database
        run: |
          bdep init -C @clang cc config.cxx=clang++
          b -vn clean update |& compiledb
 
      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../i3-settings-docs/html/

  sanity-checks:
    name: Sanity Checks
    uses: ./.github/workflows/sanity-checks
