name: Main CI

on:
  push:
    branches: [main, CI]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Build2 setup
        uses: build2/setup-build2-github-action@v2
      
      - name: Update system & install necessary tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3
          pip install compiledb
    
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - uses: wmbat/i3-settings/.github/workflows/sanity-checks.yaml

      - uses: wmbat/i3-settings/.github/workflows/documentation.yaml
