name: Pull Request CI

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Build2 setup
        uses: build2/setup-build2-github-action@v2
      
      - name: Update system & install necessary tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3
          pip install compiledb
    
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: install Build2
        uses: build2/setup-build2-github-action@v2

      - name: setup project
        run: bdep init -C ../clang @clang cc config.c=clang config.cxx=clang++

      - name: compile project
        run: b

      - name: generate compilation database
        run: b -vn clean update |& compiledb

      - name: run unit tests
        run: b test

      - name: clang-format style check
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '13'

      - name: clang-tidy
        run: run-clang-tidy -p "./" 
