name: Sanity Checks

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate compilation database
        run: |
          bdep init -C @clang cc config.cxx=clang++
          b test

      - name: Clang-tidy Checks
        run: run-clang-tidy -p "./"
