name: Sanity Checks

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update system & install necessary tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install doxygen
          sudo apt-get -y install python3
          pip install compiledb
    
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13

      - name: Get build2
        uses: actions/download-artifact@v3
        with:
          name: build2-artifact

      - name: Generate compilation database
        run: |
          sudo bdep init -C @clang cc config.cxx=clang++
          sudo b test
